model_name: Siren
N_spat: 64
N_ic: 64
N_temp: 8
N_bound: 64
MAX_EPOCH: 5
batch_size: 4096
C:
  {fidelity: 1,
    ic: 1,
    bc: 1}
P:
  {fidelity: 2,
    ic: 1,
    bc: 1,}
sched_dict: null
optimizer_config:
  {type: Adam,
    lr: 0.000001,
    weight_decay: 0}
cam_man: True
checkpoint: True
num_layer: 1
hidden_features: 200
sample_method: 'uniform'
t_max: 0.001
x_max: 1
y_max: 1
x_min: -1
y_min: -1