model_name: Siren
train_scheme: ['ic_grad']
N_spat: 128
N_ic: 128
N_temp: 8
N_bound: 128
MAX_EPOCH: 20000
batch_size: 4096
C:
  {fidelity: 0.01,
    ic: 1,
    ic_grad: 0.1,
    bc: 1}
P:
  {fidelity: 2,
    ic: 1,
    ic_grad: 2,
    bc: 1,}
sched_dict: {type: 'step', step: 1000, gamma: 0.8}
optimizer_config:
  {type: Adam,
    lr: 0.00005,
    weight_decay: 0.000001}
cam_man: True
checkpoint: True
num_layers: 4
hidden_features: 200
sample_method: 'uniform'
t_max: 0.001
x_max: 1
y_max: 1
x_min: -1
y_min: -1